import React, { createContext, useContext, useState, useEffect } from 'react';
import { SupportedLanguage } from '../types';

export interface LanguageOption {
  code: SupportedLanguage;
  name: string;
  nativeName: string;
  dir: 'ltr' | 'rtl';
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', dir: 'ltr' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', dir: 'rtl' },
  { code: 'fr', name: 'French', nativeName: 'Français', dir: 'ltr' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', dir: 'ltr' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', dir: 'ltr' },
];

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  direction: 'ltr' | 'rtl';
  t: (key: string, defaultText?: string) => string;
  getToolName: (slug: string, defaultName?: string) => string;
  getToolDesc: (slug: string, defaultDesc?: string) => string;
  getCategoryName: (slugOrId: string, defaultName?: string) => string;
  getCategoryDesc: (slugOrId: string, defaultDesc?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Core translation strings dictionary
const TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.tools': 'Tools',
    'nav.categories': 'Categories',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.search': 'Search for a tool...',
    'nav.selectLanguage': 'Select Language',
    'brand.tagline': 'Simple tools. Instant results.',
    'badge.clientPrivacy': 'Zero Server Uploads • 100% Client-Side Speed',
    'hero.title': 'Simple tools. Instant results.',
    'hero.subtitle': 'Free online tools for developers, creators, businesses and everyday tasks.',
    'hero.searchPlaceholder': 'Search for a tool... (e.g. json, image, time, percentage)',
    'btn.search': 'Search',
    'btn.clear': 'Clear',
    'btn.openTool': 'Open Tool',
    'btn.tryTool': 'Try Tool',
    'btn.copy': 'Copy',
    'btn.copied': 'Copied!',
    'btn.reset': 'Reset',
    'btn.loadExample': 'Load Example',
    'btn.calculate': 'Calculate Result',
    'btn.download': 'Download',
    'btn.format': 'Format JSON',
    'btn.minify': 'Minify JSON',
    'btn.allCategories': 'All Categories',
    'btn.viewAllTools': 'View all tools',
    'home.popularTitle': 'Popular Free Online Tools',
    'home.popularSubtitle': 'The most utilized utilities, built for instant in-browser performance.',
    'home.categoriesTitle': 'Browse by Category',
    'home.categoriesSubtitle': 'Find the exact utility you need organized across functional categories.',
    'home.whyTitle': 'Why Choose Toolora?',
    'home.whySubtitle': 'Built for speed, privacy, and zero friction.',
    'home.feature1Title': '100% In-Browser Privacy',
    'home.feature1Desc': 'Your data and files never leave your computer. Processing happens locally in your browser memory with zero server uploads.',
    'home.feature2Title': 'Instant Results',
    'home.feature2Desc': 'Experience zero latency. No waiting for server queues or file uploads; results appear in milliseconds.',
    'home.feature3Title': 'Free Forever & No Sign-up',
    'home.feature3Desc': 'Enjoy unrestricted access to all utilities without creating accounts, entering emails, or paying subscriptions.',
    'home.faqsTitle': 'Frequently Asked Questions',
    'home.faq1Q': 'Is Toolora completely free to use?',
    'home.faq1A': 'Yes! All tools on Toolora are 100% free with no account registration, subscriptions, or hidden paywalls required.',
    'home.faq2Q': 'How does Toolora protect my data privacy?',
    'home.faq2A': 'All our tools run purely on the client side using your web browser’s native computing power. Your inputs and images never touch a backend server or database.',
    'home.faq3Q': 'Do I need to install any software or extensions?',
    'home.faq3A': 'No. Toolora works directly inside any modern web browser across desktop, laptop, tablet, and mobile devices.',
    'home.faq4Q': 'Can I use Toolora offline?',
    'home.faq4A': 'Because the core computation logic runs directly in your browser, once a tool page is loaded in your browser cache, most computations can continue running without a continuous internet connection.',
    'tools.allTools': 'All Online Tools',
    'tools.allToolsDesc': 'Browse our suite of fast, client-side tools designed for instant results with zero accounts and zero downloads.',
    'tools.searchPlaceholder': 'Filter tools by name, tag, or function...',
    'tools.noResults': 'No matching tools found',
    'tools.count': 'Tools',
    'search.modalTitle': 'Quick Tool Search',
    'search.modalPlaceholder': 'Type a tool name, format, or category...',
    'search.matchingTools': 'Matching Tools',
    'search.popularTools': 'Popular Tools',
    'search.pressEsc': 'Press Esc to close',
    'footer.popularTools': 'Popular Tools',
    'footer.categories': 'Categories',
    'footer.platform': 'Platform & Legal',
    'footer.about': 'About Toolora',
    'footer.contact': 'Contact & Feedback',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cookies': 'Cookie Policy',
    'footer.allRights': 'All rights reserved.',
    'footer.privacyBadge': '100% In-Browser Privacy • Zero Server Data Upload',
    // Tool Names & Descriptions
    'tool.json-formatter.name': 'JSON Formatter & Validator',
    'tool.json-formatter.desc': 'Format, beautify, validate, and minify JSON online. Fast, secure, and completely browser-based.',
    'tool.image-resizer.name': 'Image Resizer & Compressor',
    'tool.image-resizer.desc': 'Resize, compress, and convert images online for free. Adjust dimensions, change format, and reduce file size.',
    'tool.time-zone-converter.name': 'Time Zone Converter & Meeting Planner',
    'tool.time-zone-converter.desc': 'Compare world times, schedule international meetings, and convert time across global cities in real-time.',
    'tool.percentage-calculator.name': 'Percentage Calculator',
    'tool.percentage-calculator.desc': 'Calculate percentages, percentage change, price increases, discounts, and differences with formulas.',
    'tool.business-days-calculator.name': 'Business Days Calculator',
    'tool.business-days-calculator.desc': 'Calculate working days between dates or project deadline completion with custom weekend and holiday exclusions.',
    // Categories Names & Descriptions
    'cat.developer-tools.name': 'Developer Tools',
    'cat.developer-tools.desc': 'Format, validate, encode, and debug code and data payloads directly in your browser.',
    'cat.image-tools.name': 'Image Tools',
    'cat.image-tools.desc': 'Resize, compress, convert, and crop images with 100% in-browser privacy.',
    'cat.calculators.name': 'Calculators',
    'cat.calculators.desc': 'Fast, precise everyday and business calculation tools with step-by-step formulas.',
    'cat.date-and-time.name': 'Date & Time',
    'cat.date-and-time.desc': 'Convert time zones, compute business days, count days, and plan schedules across cities.',
    'cat.text-tools.name': 'Text Tools',
    'cat.text-tools.desc': 'Count words, convert casing, clean text, and format strings effortlessly.',
    'cat.converters.name': 'Converters',
    'cat.converters.desc': 'Convert units, data storage, length, temperature, and currency seamlessly.',
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.tools': 'الأدوات',
    'nav.categories': 'التصنيفات',
    'nav.about': 'عن المنصة',
    'nav.contact': 'اتصل بنا',
    'nav.search': 'ابحث عن أداة...',
    'nav.selectLanguage': 'اختر اللغة',
    'brand.tagline': 'أدوات بسيطة. نتائج فورية.',
    'badge.clientPrivacy': 'بدون رفع إلى الخادم • سرعة وأمان 100% داخل المتصفح',
    'hero.title': 'أدوات بسيطة. نتائج فورية.',
    'hero.subtitle': 'أدوات مجانية عبر الإنترنت للمطورين، وصناع المحتوى، والشركات، والمهام اليومية.',
    'hero.searchPlaceholder': 'ابحث عن أداة... (مثل json، صورة، وقت، نسبة مئوية)',
    'btn.search': 'بحث',
    'btn.clear': 'مسح',
    'btn.openTool': 'فتح الأداة',
    'btn.tryTool': 'تجربة الأداة',
    'btn.copy': 'نسخ',
    'btn.copied': 'تم النسخ!',
    'btn.reset': 'إعادة ضبط',
    'btn.loadExample': 'تحميل مثال',
    'btn.calculate': 'حساب النتيجة',
    'btn.download': 'تحميل',
    'btn.format': 'تنسيق JSON',
    'btn.minify': 'ضغط JSON',
    'btn.allCategories': 'جميع التصنيفات',
    'btn.viewAllTools': 'عرض جميع الأدوات',
    'home.popularTitle': 'أشهر الأدوات المجانية عبر الإنترنت',
    'home.popularSubtitle': 'أدوات مميزة مصممة لأداء فوري فائق ومعالجة آمنة داخل متصفحك.',
    'home.categoriesTitle': 'تصفح الأدوات حسب التصنيف',
    'home.categoriesSubtitle': 'اعثر بسرعة على الأداة المناسبة لك من بين تصنيفات متخصصة ومفيدة.',
    'home.whyTitle': 'لماذا تختار Toolora؟',
    'home.whySubtitle': 'صُممت لتمنحك سرعة فائقة، خصوصية مطلقة، وبدون أي تعقيد.',
    'home.feature1Title': 'خصوصية تامة 100% داخل المتصفح',
    'home.feature1Desc': 'بياناتك وملفاتك لا تغادر جهازك أبداً. تتم جميع المعالجات محلياً في ذاكرة متصفحك دون إرسال أي بيانات إلى خوادم خارجية.',
    'home.feature2Title': 'نتائج فورية بدون انتظار',
    'home.feature2Desc': 'معالجة محلية بدون أي تأخير، دون الحاجة لانتظار قوائم الخوادم أو أوقات الرفع الطويلة.',
    'home.feature3Title': 'مجاني دائماً وبدون تسجيل',
    'home.feature3Desc': 'استخدم جميع الأدوات مجاناً دون الحاجة لإنشاء حساب أو إدخال بريدك الإلكتروني أو دفع أي رسوم.',
    'home.faqsTitle': 'الأسئلة الشائعة',
    'home.faq1Q': 'هل استخدام Toolora مجاني بالكامل؟',
    'home.faq1A': 'نعم! جميع الأدوات على Toolora مجانية 100% بدون أي رسوم خفية أو قيود أو اشتراكات.',
    'home.faq2Q': 'كيف تحمي Toolora خصوصية بياناتي؟',
    'home.faq2A': 'تعتمد جميع أدواتنا على المعالجة المحلية التامة داخل متصفحك. لا يتم تخزين أو رفع أي نصوص أو صور أو بيانات إلى أي خادم.',
    'home.faq3Q': 'هل أحتاج لتثبيت أي برامج أو ملحقات؟',
    'home.faq3A': 'لا، تعمل المنصة بشكل مباشر على أي متصفح ويب حديث سواء على أجهزة الكمبيوتر أو الهواتف الذكية والأجهزة اللوحية.',
    'home.faq4Q': 'هل يمكنني استخدام الأدوات دون اتصال بالإنترنت؟',
    'home.faq4A': 'نظراً لأن جميع الحسابات والمعالجات تتم داخل متصفحك، بمجرد تحميل صفحة الأداة يمكنك الاستمرار في استخدامها حتى لو انقطع الاتصال.',
    'tools.allTools': 'جميع الأدوات عبر الإنترنت',
    'tools.allToolsDesc': 'استعرض مجموعتنا من الأدوات السريعة المصممة لنتائج فورية بدون حسابات وبدون تنزيل برامج.',
    'tools.searchPlaceholder': 'ابحث عن أداة بالاسم أو الوظيفة أو الوسم...',
    'tools.noResults': 'لا توجد أدوات تطابق بحثك',
    'tools.count': 'أدوات',
    'search.modalTitle': 'البحث السريع عن الأدوات',
    'search.modalPlaceholder': 'اكتب اسم أداة أو صيغة أو تصنيف...',
    'search.matchingTools': 'أدوات مطابقة للبحث',
    'search.popularTools': 'الأدوات الأكثر استخداماً',
    'search.pressEsc': 'اضغط Esc للإغلاق',
    'footer.popularTools': 'الأدوات الشائعة',
    'footer.categories': 'التصنيفات',
    'footer.platform': 'المنصة والقانون',
    'footer.about': 'عن Toolora',
    'footer.contact': 'اتصل بنا والآراء',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الخدمة',
    'footer.cookies': 'سياسة ملفات تعريف الارتباط',
    'footer.allRights': 'جميع الحقوق محفوظة.',
    'footer.privacyBadge': 'خصوصية 100% داخل المتصفح • بدون رفع بيانات للخادم',
    // Tool Names & Descriptions
    'tool.json-formatter.name': 'منسق ومدقق JSON',
    'tool.json-formatter.desc': 'تنسيق وتجميل والتحقق من صحة وضغط كود JSON فورياً وبأمان تام داخل المتصفح.',
    'tool.image-resizer.name': 'مغير حجم وضغط الصور',
    'tool.image-resizer.desc': 'تغيير حجم الصور وضغطها وتحويل صيغها مجاناً. ضبط الأبعاد وتقليل حجم الملف بدون فقدان الجودة.',
    'tool.time-zone-converter.name': 'محول المناطق الزمنية ومخطط الاجتماعات',
    'tool.time-zone-converter.desc': 'مقارنة التوقيت العالمي وجدولة الاجتماعات الدولية وتحويل الوقت بين مدن العالم بدقة ولحظياً.',
    'tool.percentage-calculator.name': 'حاسبة النسبة المئوية',
    'tool.percentage-calculator.desc': 'حساب النسب المئوية، الزيادة والنقصان، الخصومات والفروقات مع خطوات الحل والمعادلات الرياضية.',
    'tool.business-days-calculator.name': 'حاسبة أيام العمل',
    'tool.business-days-calculator.desc': 'حساب عدد أيام العمل بين تاريخين أو تحديد تاريخ التسليم مع استبعاد عطلات نهاية الأسبوع والأعياد.',
    // Categories Names & Descriptions
    'cat.developer-tools.name': 'أدوات المطورين',
    'cat.developer-tools.desc': 'تنسيق والتحقق من صحة وتشفير واستكشاف أخطاء البيانات والأكواد في متصفحك.',
    'cat.image-tools.name': 'أدوات الصور',
    'cat.image-tools.desc': 'تغيير الحجم وضغط وتحويل الصور بخصوصية تامة 100% داخل المتصفح.',
    'cat.calculators.name': 'الآلات الحاسبة',
    'cat.calculators.desc': 'أدوات حسابية سريعة ودقيقة للأعمال والمهام اليومية مع عرض خطوات الحل.',
    'cat.date-and-time.name': 'الوقت والتاريخ',
    'cat.date-and-time.desc': 'تحويل المناطق الزمنية، حساب أيام العمل، عد الأيام وتخطيط المواعيد بين المدن.',
    'cat.text-tools.name': 'أدوات النصوص',
    'cat.text-tools.desc': 'حساب الكلمات، تحويل حالة الأحرف، تنظيف وتنسيق النصوص بكل سهولة.',
    'cat.converters.name': 'المحولات',
    'cat.converters.desc': 'تحويل الوحدات، وحدات التخزين، الأطوال، درجات الحرارة والمزيد بكل سلاسة.',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.tools': 'Outils',
    'nav.categories': 'Catégories',
    'nav.about': 'À propos',
    'nav.contact': 'Contact',
    'nav.search': 'Rechercher un outil...',
    'nav.selectLanguage': 'Choisir la langue',
    'brand.tagline': 'Des outils simples. Des résultats instantanés.',
    'badge.clientPrivacy': 'Zéro envoi serveur • 100% Rapide & Local',
    'hero.title': 'Des outils simples. Des résultats instantanés.',
    'hero.subtitle': 'Outils en ligne gratuits pour développeurs, créateurs, entreprises et tâches du quotidien.',
    'hero.searchPlaceholder': 'Rechercher un outil... (ex: json, image, temps, pourcentage)',
    'btn.search': 'Rechercher',
    'btn.clear': 'Effacer',
    'btn.openTool': 'Ouvrir l\'outil',
    'btn.tryTool': 'Essayer',
    'btn.copy': 'Copier',
    'btn.copied': 'Copié !',
    'btn.reset': 'Réinitialiser',
    'btn.loadExample': 'Exemple',
    'btn.calculate': 'Calculer le résultat',
    'btn.download': 'Télécharger',
    'btn.format': 'Formater JSON',
    'btn.minify': 'Compresser JSON',
    'btn.allCategories': 'Toutes les catégories',
    'btn.viewAllTools': 'Voir tous les outils',
    'home.popularTitle': 'Outils Populaires Gratuits',
    'home.popularSubtitle': 'Les utilitaires les plus utilisés, conçus pour des performances instantanées.',
    'home.categoriesTitle': 'Parcourir par Catégorie',
    'home.categoriesSubtitle': 'Trouvez l\'outil exact dont vous avez besoin parmi nos catégories dédiées.',
    'home.whyTitle': 'Pourquoi choisir Toolora ?',
    'home.whySubtitle': 'Conçu pour la rapidité, la confidentialité et la simplicité absolue.',
    'home.feature1Title': '100% Privé dans le Navigateur',
    'home.feature1Desc': 'Vos fichiers et données ne quittent jamais votre appareil. Traitement 100% local en mémoire.',
    'home.feature2Title': 'Résultats Instantanés',
    'home.feature2Desc': 'Zéro latence. Aucune file d\'attente serveur : vos résultats s\'affichent en millisecondes.',
    'home.feature3Title': 'Gratuit & Sans Inscription',
    'home.feature3Desc': 'Accès illimité à tous les outils sans création de compte, sans email et sans frais.',
    'home.faqsTitle': 'Foire Aux Questions',
    'home.faq1Q': 'Toolora est-il entièrement gratuit ?',
    'home.faq1A': 'Oui ! Tous les outils sont 100% gratuits, sans abonnement ni frais cachés.',
    'home.faq2Q': 'Comment Toolora protège-t-il ma vie privée ?',
    'home.faq2A': 'Nos outils s\'exécutent exclusivement côté client dans votre navigateur sans toucher aucun serveur.',
    'home.faq3Q': 'Dois-je installer une application ou extension ?',
    'home.faq3A': 'Non. Toolora fonctionne directement dans votre navigateur web sur mobile, tablette et ordinateur.',
    'home.faq4Q': 'Puis-je utiliser les outils hors ligne ?',
    'home.faq4A': 'Oui, une fois la page chargée dans le cache de votre navigateur, les calculs fonctionnent hors ligne.',
    'tools.allTools': 'Tous les Outils en Ligne',
    'tools.allToolsDesc': 'Explorez notre suite d\'outils rapides conçus pour des résultats instantanés sans inscription.',
    'tools.searchPlaceholder': 'Filtrer par nom, fonction ou tag...',
    'tools.noResults': 'Aucun outil correspondant',
    'tools.count': 'Outils',
    'search.modalTitle': 'Recherche Rapide d\'Outils',
    'search.modalPlaceholder': 'Tapez un nom d\'outil, format ou catégorie...',
    'search.matchingTools': 'Outils correspondants',
    'search.popularTools': 'Outils populaires',
    'search.pressEsc': 'Appuyez sur Échap pour fermer',
    'footer.popularTools': 'Outils Populaires',
    'footer.categories': 'Catégories',
    'footer.platform': 'Plateforme & Légal',
    'footer.about': 'À propos de Toolora',
    'footer.contact': 'Contact & Retours',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.terms': 'Conditions d\'Utilisation',
    'footer.cookies': 'Gestion des Cookies',
    'footer.allRights': 'Tous droits réservés.',
    'footer.privacyBadge': 'Confidentialité 100% Locale • Zéro Upload Serveur',
    // Tool Names & Descriptions
    'tool.json-formatter.name': 'Formateur & Validateur JSON',
    'tool.json-formatter.desc': 'Formatez, validez et compressez vos fichiers JSON directement et en toute sécurité dans le navigateur.',
    'tool.image-resizer.name': 'Redimensionneur & Compresseur d\'Image',
    'tool.image-resizer.desc': 'Redimensionnez, compressez et convertissez vos images gratuitement et instantanément.',
    'tool.time-zone-converter.name': 'Convertisseur de Fuseaux Horaires',
    'tool.time-zone-converter.desc': 'Comparez les heures mondiales et planifiez des réunions internationales en temps réel.',
    'tool.percentage-calculator.name': 'Calculateur de Pourcentage',
    'tool.percentage-calculator.desc': 'Calculez des pourcentages, augmentations, réductions et différences avec étapes de résolution.',
    'tool.business-days-calculator.name': 'Calculateur de Jours Ouvrés',
    'tool.business-days-calculator.desc': 'Calculez les jours ouvrés entre deux dates avec week-ends et jours fériés personnalisables.',
    // Categories Names & Descriptions
    'cat.developer-tools.name': 'Outils Développeur',
    'cat.developer-tools.desc': 'Formatez, validez, encodez et déboguez du code et des données dans votre navigateur.',
    'cat.image-tools.name': 'Outils Image',
    'cat.image-tools.desc': 'Redimensionnez, compressez et convertissez vos images en toute confidentialité.',
    'cat.calculators.name': 'Calculateurs',
    'cat.calculators.desc': 'Des outils de calcul rapides et précis pour le quotidien et les affaires avec formules.',
    'cat.date-and-time.name': 'Date & Heure',
    'cat.date-and-time.desc': 'Convertissez les fuseaux horaires, calculez les jours ouvrés et planifiez vos dates.',
    'cat.text-tools.name': 'Outils Texte',
    'cat.text-tools.desc': 'Comptez les mots, changez la casse et nettoyez vos textes facilement.',
    'cat.converters.name': 'Convertisseurs',
    'cat.converters.desc': 'Convertissez facilement les unités de mesure, stockage, longueurs et devises.',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.tools': 'Herramientas',
    'nav.categories': 'Categorías',
    'nav.about': 'Acerca de',
    'nav.contact': 'Contacto',
    'nav.search': 'Buscar una herramienta...',
    'nav.selectLanguage': 'Seleccionar Idioma',
    'brand.tagline': 'Herramientas simples. Resultados instantáneos.',
    'badge.clientPrivacy': 'Cero subidas al servidor • 100% Rápido en tu Navegador',
    'hero.title': 'Herramientas simples. Resultados instantáneos.',
    'hero.subtitle': 'Herramientas en línea gratuitas para desarrolladores, creadores, empresas y tareas cotidianas.',
    'hero.searchPlaceholder': 'Buscar una herramienta... (ej: json, imagen, tiempo, porcentaje)',
    'btn.search': 'Buscar',
    'btn.clear': 'Borrar',
    'btn.openTool': 'Abrir herramienta',
    'btn.tryTool': 'Probar',
    'btn.copy': 'Copiar',
    'btn.copied': '¡Copiado!',
    'btn.reset': 'Restablecer',
    'btn.loadExample': 'Cargar ejemplo',
    'btn.calculate': 'Calcular resultado',
    'btn.download': 'Descargar',
    'btn.format': 'Formatear JSON',
    'btn.minify': 'Minificar JSON',
    'btn.allCategories': 'Todas las categorías',
    'btn.viewAllTools': 'Ver todas las herramientas',
    'home.popularTitle': 'Herramientas Gratuitas Populares',
    'home.popularSubtitle': 'Las utilidades más utilizadas, diseñadas para un rendimiento instantáneo en el navegador.',
    'home.categoriesTitle': 'Explorar por Categoría',
    'home.categoriesSubtitle': 'Encuentre la utilidad exacta que necesita organizada por categorías funcionales.',
    'home.whyTitle': '¿Por qué elegir Toolora?',
    'home.whySubtitle': 'Diseñado para ofrecer máxima velocidad, privacidad absoluta y sin complicaciones.',
    'home.feature1Title': '100% Privacidad en el Navegador',
    'home.feature1Desc': 'Sus datos y archivos nunca salen de su computadora. El procesamiento es totalmente local en memoria.',
    'home.feature2Title': 'Resultados Instantáneos',
    'home.feature2Desc': 'Sin demoras ni colas de espera en servidores; obtenga sus resultados en milisegundos.',
    'home.feature3Title': 'Gratis para Siempre y sin Registro',
    'home.feature3Desc': 'Acceso ilimitado a todas las utilidades sin suscripciones ni necesidad de crear cuentas.',
    'home.faqsTitle': 'Preguntas Frecuentes',
    'home.faq1Q': '¿Es Toolora completamente gratuito?',
    'home.faq1A': '¡Sí! Todas las herramientas son 100% gratuitas, sin registros obligatorios ni cargos ocultos.',
    'home.faq2Q': '¿Cómo protege Toolora mi privacidad?',
    'home.faq2A': 'Todas las herramientas se ejecutan localmente en su navegador sin enviar ningún archivo ni texto a servidores.',
    'home.faq3Q': '¿Necesito instalar software o extensiones?',
    'home.faq3A': 'No. Toolora funciona directamente en cualquier navegador moderno en ordenadores y móviles.',
    'home.faq4Q': '¿Puedo usar Toolora sin conexión a Internet?',
    'home.faq4A': 'Sí, una vez cargada la página, la mayoría de herramientas continúan funcionando sin conexión.',
    'tools.allTools': 'Todas las Herramientas en Línea',
    'tools.allToolsDesc': 'Explore nuestra colección de herramientas rápidas para resultados instantáneos.',
    'tools.searchPlaceholder': 'Filtrar por nombre, etiqueta o función...',
    'tools.noResults': 'No se encontraron herramientas coincidentes',
    'tools.count': 'Herramientas',
    'search.modalTitle': 'Búsqueda Rápida de Herramientas',
    'search.modalPlaceholder': 'Escriba un nombre, formato o categoría...',
    'search.matchingTools': 'Herramientas coincidentes',
    'search.popularTools': 'Herramientas populares',
    'search.pressEsc': 'Presione Esc para cerrar',
    'footer.popularTools': 'Herramientas Populares',
    'footer.categories': 'Categorías',
    'footer.platform': 'Plataforma y Legal',
    'footer.about': 'Acerca de Toolora',
    'footer.contact': 'Contacto y Opiniones',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos del Servicio',
    'footer.cookies': 'Política de Cookies',
    'footer.allRights': 'Todos los derechos reservados.',
    'footer.privacyBadge': 'Privacidad 100% en el Navegador • Cero Subidas de Datos',
    // Tool Names & Descriptions
    'tool.json-formatter.name': 'Formateador y Validador JSON',
    'tool.json-formatter.desc': 'Formatee, valide y comprima JSON en línea de forma rápida y segura en su navegador.',
    'tool.image-resizer.name': 'Redimensionador y Compresor de Imágenes',
    'tool.image-resizer.desc': 'Cambie el tamaño, comprima y convierta imágenes gratis en línea al instante.',
    'tool.time-zone-converter.name': 'Convertidor de Zonas Horarias',
    'tool.time-zone-converter.desc': 'Compare horarios mundiales y planifique reuniones internacionales fácilmente.',
    'tool.percentage-calculator.name': 'Calculadora de Porcentajes',
    'tool.percentage-calculator.desc': 'Calcule porcentajes, aumentos, descuentos y diferencias con fórmulas paso a paso.',
    'tool.business-days-calculator.name': 'Calculadora de Días Hábiles',
    'tool.business-days-calculator.desc': 'Calcule días laborables entre fechas excluyendo fines de semana y festivos.',
    // Categories Names & Descriptions
    'cat.developer-tools.name': 'Herramientas de Desarrollo',
    'cat.developer-tools.desc': 'Formatee, valide y depure código y datos directamente en su navegador.',
    'cat.image-tools.name': 'Herramientas de Imagen',
    'cat.image-tools.desc': 'Redimensione, comprima y convierta imágenes con privacidad 100% local.',
    'cat.calculators.name': 'Calculadoras',
    'cat.calculators.desc': 'Herramientas de cálculo rápidas y precisas con fórmulas paso a paso.',
    'cat.date-and-time.name': 'Fecha y Hora',
    'cat.date-and-time.desc': 'Convierta zonas horarias, calcule días laborables y planifique fechas.',
    'cat.text-tools.name': 'Herramientas de Texto',
    'cat.text-tools.desc': 'Cuente palabras, cambie mayúsculas/minúsculas y limpie textos fácilmente.',
    'cat.converters.name': 'Conversores',
    'cat.converters.desc': 'Convierta unidades de medida, almacenamiento, longitud y temperatura.',
  },
  de: {
    'nav.home': 'Startseite',
    'nav.tools': 'Werkzeuge',
    'nav.categories': 'Kategorien',
    'nav.about': 'Über uns',
    'nav.contact': 'Kontakt',
    'nav.search': 'Werkzeug suchen...',
    'nav.selectLanguage': 'Sprache wählen',
    'brand.tagline': 'Einfache Werkzeuge. Sofortige Ergebnisse.',
    'badge.clientPrivacy': 'Keine Server-Uploads • 100% Lokal & Schnell',
    'hero.title': 'Einfache Werkzeuge. Sofortige Ergebnisse.',
    'hero.subtitle': 'Kostenlose Online-Werkzeuge für Entwickler, Kreative, Unternehmen und Alltagsaufgaben.',
    'hero.searchPlaceholder': 'Werkzeug suchen... (z. B. json, bild, zeit, prozent)',
    'btn.search': 'Suchen',
    'btn.clear': 'Löschen',
    'btn.openTool': 'Werkzeug öffnen',
    'btn.tryTool': 'Ausprobieren',
    'btn.copy': 'Kopieren',
    'btn.copied': 'Kopiert!',
    'btn.reset': 'Zurücksetzen',
    'btn.loadExample': 'Beispiel laden',
    'btn.calculate': 'Ergebnis berechnen',
    'btn.download': 'Herunterladen',
    'btn.format': 'JSON formatieren',
    'btn.minify': 'JSON minimieren',
    'btn.allCategories': 'Alle Kategorien',
    'btn.viewAllTools': 'Alle Werkzeuge anzeigen',
    'home.popularTitle': 'Beliebte Kostenlose Online-Werkzeuge',
    'home.popularSubtitle': 'Die meistgenutzten Werkzeuge, entwickelt für blitzschnelle Ausführung im Browser.',
    'home.categoriesTitle': 'Nach Kategorie durchsuchen',
    'home.categoriesSubtitle': 'Finden Sie genau das passende Werkzeug übersichtlich nach Kategorien sortiert.',
    'home.whyTitle': 'Warum Toolora wählen?',
    'home.whySubtitle': 'Entwickelt für Geschwindigkeit, absolute Privatsphäre und mühelose Nutzung.',
    'home.feature1Title': '100% Datenschutz im Browser',
    'home.feature1Desc': 'Ihre Daten und Dateien verlassen nie Ihr Gerät. Die Verarbeitung erfolgt rein lokal im Browser-Speicher.',
    'home.feature2Title': 'Sofortige Ergebnisse',
    'home.feature2Desc': 'Keine Server-Wartezeiten oder Upload-Verzögerungen; Berechnungen in Millisekunden.',
    'home.feature3Title': 'Dauerhaft Kostenlos & Ohne Anmeldung',
    'home.feature3Desc': 'Unbegrenzter Zugriff auf alle Tools ohne Kontoerstellung, ohne E-Mail und ohne Abokosten.',
    'home.faqsTitle': 'Häufig Gestellte Fragen',
    'home.faq1Q': 'Ist Toolora wirklich kostenlos?',
    'home.faq1A': 'Ja! Alle Werkzeuge auf Toolora sind zu 100% kostenlos ohne versteckte Gebühren oder Abos.',
    'home.faq2Q': 'Wie schützt Toolora meine Daten?',
    'home.faq2A': 'Alle Berechnungen laufen lokal in Ihrem Webbrowser. Es werden keinerlei Daten an Server übertragen.',
    'home.faq3Q': 'Muss ich Software oder Erweiterungen installieren?',
    'home.faq3A': 'Nein. Toolora funktioniert direkt in jedem modernen Webbrowser auf Desktop, Tablet und Smartphone.',
    'home.faq4Q': 'Kann ich Toolora offline nutzen?',
    'home.faq4A': 'Ja, sobald die Seite im Browser geladen ist, funktionieren die meisten Rechner auch ohne Internetverbindung.',
    'tools.allTools': 'Alle Online-Werkzeuge',
    'tools.allToolsDesc': 'Entdecken Sie unsere schnellen Browser-Werkzeuge für sofortige Ergebnisse.',
    'tools.searchPlaceholder': 'Nach Name, Tag oder Funktion filtern...',
    'tools.noResults': 'Keine passenden Werkzeuge gefunden',
    'tools.count': 'Werkzeuge',
    'search.modalTitle': 'Werkzeug-Schnellsuche',
    'search.modalPlaceholder': 'Werkzeugname, Format oder Kategorie eingeben...',
    'search.matchingTools': 'Passende Werkzeuge',
    'search.popularTools': 'Beliebte Werkzeuge',
    'search.pressEsc': 'Esc drücken zum Schließen',
    'footer.popularTools': 'Beliebte Werkzeuge',
    'footer.categories': 'Kategorien',
    'footer.platform': 'Plattform & Rechtliches',
    'footer.about': 'Über Toolora',
    'footer.contact': 'Kontakt & Feedback',
    'footer.privacy': 'Datenschutzerklärung',
    'footer.terms': 'Nutzungsbedingungen',
    'footer.cookies': 'Cookie-Richtlinie',
    'footer.allRights': 'Alle Rechte vorbehalten.',
    'footer.privacyBadge': '100% Privatsphäre im Browser • Keine Server-Uploads',
    // Tool Names & Descriptions
    'tool.json-formatter.name': 'JSON-Formatierer & Validierer',
    'tool.json-formatter.desc': 'JSON online formatieren, validieren und minimieren. Schnell und sicher im Browser.',
    'tool.image-resizer.name': 'Bildgröße ändern & Komprimieren',
    'tool.image-resizer.desc': 'Bilder kostenlos online skalieren, komprimieren und in andere Formate konvertieren.',
    'tool.time-zone-converter.name': 'Zeitzonen-Konverter & Terminplaner',
    'tool.time-zone-converter.desc': 'Weltzeiten vergleichen und internationale Meetings in Echtzeit planen.',
    'tool.percentage-calculator.name': 'Prozentrechner',
    'tool.percentage-calculator.desc': 'Berechnen Sie Prozentsätze, Steigerungen, Rabatte und Differenzen mit Formeln.',
    'tool.business-days-calculator.name': 'Werktage-Rechner',
    'tool.business-days-calculator.desc': 'Werktage zwischen Daten berechnen mit benutzerdefinierten Wochenenden und Feiertagen.',
    // Categories Names & Descriptions
    'cat.developer-tools.name': 'Entwickler-Werkzeuge',
    'cat.developer-tools.desc': 'Code und Daten direkt im Browser formatieren, validieren und debuggen.',
    'cat.image-tools.name': 'Bild-Werkzeuge',
    'cat.image-tools.desc': 'Bilder mit voller Privatsphäre skalieren, komprimieren und konvertieren.',
    'cat.calculators.name': 'Rechner',
    'cat.calculators.desc': 'Schnelle und präzise Rechner für Alltag und Beruf mit Schritt-für-Schritt-Lösungen.',
    'cat.date-and-time.name': 'Datum & Uhrzeit',
    'cat.date-and-time.desc': 'Zeitzonen konvertieren, Werktage berechnen und Termine planen.',
    'cat.text-tools.name': 'Text-Werkzeuge',
    'cat.text-tools.desc': 'Wörter zählen, Groß-/Kleinschreibung ändern und Texte formatieren.',
    'cat.converters.name': 'Konverter',
    'cat.converters.desc': 'Einheiten, Speichergrößen, Längen und Temperaturen einfach umrechnen.',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<SupportedLanguage>(() => {
    try {
      const saved = localStorage.getItem('toolora_lang') as SupportedLanguage;
      return saved && LANGUAGES.some((l) => l.code === saved) ? saved : 'en';
    } catch {
      return 'en';
    }
  });

  const currentOption = LANGUAGES.find((l) => l.code === language) || LANGUAGES[0];
  const direction = currentOption.dir;

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = direction;
  }, [language, direction]);

  const setLanguage = (lang: SupportedLanguage) => {
    setLanguageState(lang);
    try {
      localStorage.setItem('toolora_lang', lang);
    } catch {
      // Safe fallback if local storage is restricted
    }
  };

  const t = (key: string, defaultText = ''): string => {
    return TRANSLATIONS[language]?.[key] ?? TRANSLATIONS['en']?.[key] ?? defaultText;
  };

  const getToolName = (slug: string, defaultName = ''): string => {
    const key = `tool.${slug}.name`;
    return TRANSLATIONS[language]?.[key] ?? TRANSLATIONS['en']?.[key] ?? defaultName;
  };

  const getToolDesc = (slug: string, defaultDesc = ''): string => {
    const key = `tool.${slug}.desc`;
    return TRANSLATIONS[language]?.[key] ?? TRANSLATIONS['en']?.[key] ?? defaultDesc;
  };

  const getCategoryName = (slugOrId: string, defaultName = ''): string => {
    const key = `cat.${slugOrId}.name`;
    return TRANSLATIONS[language]?.[key] ?? TRANSLATIONS['en']?.[key] ?? defaultName;
  };

  const getCategoryDesc = (slugOrId: string, defaultDesc = ''): string => {
    const key = `cat.${slugOrId}.desc`;
    return TRANSLATIONS[language]?.[key] ?? TRANSLATIONS['en']?.[key] ?? defaultDesc;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        direction,
        t,
        getToolName,
        getToolDesc,
        getCategoryName,
        getCategoryDesc,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
